//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Simple : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean PlaceMarker
        {
            get
            {
                return SteamVR_Actions.simple_PlaceMarker;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.simple_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean chooseMarker
        {
            get
            {
                return SteamVR_Actions.simple_chooseMarker;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Resize
        {
            get
            {
                return SteamVR_Actions.simple_Resize;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate
        {
            get
            {
                return SteamVR_Actions.simple_Rotate;
            }
        }
    }
}
